#!/bin/bash
sudo apt install openjdk-17-jdk wget -y

# Create necessary directories
mkdir -p /opt/nexus/
mkdir -p /tmp/nexus/
cd /tmp/nexus/

# Download Nexus
NEXUSURL="https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
wget $NEXUSURL -O nexus.tar.gz

# Extract Nexus and capture directory name
EXTOUT=$(tar xzvf nexus.tar.gz | head -1)
NEXUSDIR=$(echo $EXTOUT | cut -d '/' -f1)

# Clean up the tarball
rm -rf /tmp/nexus/nexus.tar.gz

# Move Nexus to the desired directory
rsync -avzh /tmp/nexus/ /opt/nexus/

# Create a Nexus user
useradd nexus
chown -R nexus.nexus /opt/nexus

# Create Nexus service file with the correct directory
cat <<EOT > /etc/systemd/system/nexus.service
[Unit]
Description=nexus service
After=network.target

[Service]
Type=forking
LimitNOFILE=65536
ExecStart=/opt/nexus/$NEXUSDIR/bin/nexus start
ExecStop=/opt/nexus/$NEXUSDIR/bin/nexus stop
User=nexus
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOT

# Configure Nexus to run as nexus user
echo 'run_as_user="nexus"' > /opt/nexus/$NEXUSDIR/bin/nexus.rc

# Reload systemd, start, and enable Nexus service
systemctl daemon-reload
systemctl start nexus
systemctl enable nexus
