---
- name: Install packages on CentOS
  hosts: centos8
  become: yes
  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - wget
        - httpd
        - curl
        - chrony

