---
- name: Update NTP server details
  hosts: centos8
  become: yes
  vars:
    ntp_servers:
      - 0.asia.pool.ntp.org
      - 1.asia.pool.ntp.org
      - 2.asia.pool.ntp.org
      - 3.asia.pool.ntp.org

  tasks:
    - name: Update NTP configuration
      template:
        src: ntp.conf.j2
        dest: /etc/chrony.conf
      notify:
        - Restart chronyd

  handlers:
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted

